### ISSUE TITLE
Why not using pins_arduino.h?

### ISSUE THREAD

**Issue by mralexgray** [fenichelar/Pin#4]
So, as for using `pins_arduino.h`... everyone else does...  Why not here?  Makes it "just work" - for any platform (`AVR`-only, at this point, _I'd guess_) that has an existing pin mapping definition.  _This_ format _does_ work, but is cryptic and reinvents the wheel.  Is there a reason for it (i.e.. you **need** the user to tell you where the registers are, etc?)

**Comment by fenichelar** [comment]
I made this library in a rush for another project (I needed fast I/O). It ended up not even being fast enough (inline assembly sucks but is really fast). I had an issue with using those macros so I just did it manually, can't remember what the problem was.

**Comment by fenichelar** [comment]
Checkout the latest commits. I haven't tested (other than confirming the examples build). I'll test with hardware in the next few days and release.

**Comment by mralexgray** [comment]
I agree those macros suck..  some of them are straight up oxymoronic... moronic being the key word...  but.... they exist, and are maintained, usually, at least..  sometimes easier to just use whatever crappy infrastructure is there, if it is sufficient...  will test myself, as well.

**Comment by fenichelar** [comment]
I completely agree, it took a few minutes to understand what they were even doing. Definitely could be using them incorrectly. Thanks for testing.

Thanks for testing. Are you just manually including the board specific mapping for your project with different boards? Trying to think of the best way to use both boards files and the Arduino marcos.

**Comment by fenichelar** [comment]
I think this will work.... add `#define Board_H` to your board files and if you include them it will use it otherwise it reverts to Arduino macros. 65925bf95ed4f5c6c8a69bb7d02b81a4121ddb31
