### ISSUE TITLE
Clarify different between state and value, if any.

### ISSUE THREAD

**Issue by mralexgray** [fenichelar/Pin#7]
Why are there two sets of functions/variables for `state` and `value`?  Are they not he same thing (`HIGH`/`LOW`)?

**Comment by fenichelar** [comment]
Each pin has three registers: DDR, PORT, PIN.

DDR: data direction - input or output
PORT: if DDR is set to output, this is what you use to set the output. if DDR is set to input, this is what you use to turn the pullup resistor on and off.
PIN: read only. This is how you read the input if DDR is set to input. If DDR is set to output, this will just be the same as the output.

mode = DDR
state = PORT
value = PIN
