### ISSUE TITLE
Compiler error if Pin object is not defined.

### ISSUE THREAD

**Issue by megablue** [fenichelar/Pin#8]
If I ever tried to define the object first and try to initialize the object later.

say...

Pin ledPin;

it will result in a compiler error "no matching function for call to Pin::Pin() 
because it doesn't have a default constructor...

**Comment by fenichelar** [comment]
@megablue Sorry for the delay. A default constructor has been added to Pin which defaults to pin 0. Version 4.2.0 includes this change and has been released.
